apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  namespace: roboshop
  labels:
    environment: production
    app: nginx
   
spec:
  containers:
  - name: nginx
    image: nginx
  - name: sidecar
    image: almalinux:8
    command:
      - sleep
      - "200"
