apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
  namespace: roboshop
  annotations:
    com.project.author: Prasanthi
    com.project.name: roboshop
spec:
  containers:
  - name: nginx-simple
    image: nginx:1.14.2
    ports:
    - containerPort: 80