apiVersion: v1
kind: Pod
metadata: 
  name: config-pod
  namespace: roboshop
spec:
  containers:
  - name: configmap-demo
    image: nginx
    env:
    - name: Course
      valueFrom:
        configMapKeyRef:
          name: course-config
          key: Course
    - name: Tutor
      valueFrom:
        configMapKeyRef:
          name: course-config
          key: Tutor 

      