apiVersion: v1
kind: Pod
metadata:
  name: secret-pod-direct
  namespace: roboshop
spec:
  containers:
  - name: secret-pod-direct
    image: nginx
    envFrom:
      - secretRef:
          name: secret